"""Cross-package import gate (PS-140) for scitex-notification.

Every module listed here is imported by this package's source but
OWNED by a peer standalone. A rename or move on the other side of
that boundary is invisible to this package's unit tests and
surfaces as ModuleNotFoundError in a user's process — which is how
the `scitex_io._load_cache` rename went undetected for weeks.

Generated by `scitex-dev ecosystem install-cross-package-gate`.

generated-by: scitex-dev 0.60.2.dev27+g1d7cc9877

A GATE NOBODY CAN DATE IS A CLAIM ABOUT AN UNKNOWN PAST. This
list is a snapshot of the cross-package imports as they stood
when the stamp above was written; it does not update itself, and
a stale copy looks exactly like a current one. Measured
2026-08-16: 17 gates across the fleet carried NO stamp and named
a generator that never existed as a command -- the real writer
was a one-shot script since deleted -- so the only way to tell a
fossil from a live gate was a filesystem sweep of mtimes. The
same disease had already been found in the audit gate (68 of 70
still calling audit_all_for_package() with no path=), and the
same cure applies: say which version wrote you.

Regenerate with:

    scitex-dev ecosystem install-cross-package-gate scitex-notification --force

Do not hand-edit the list: the PS-140 auditor recomputes it from
source on every run and fails on any drift in either direction
(a missing entry OR a stale one).

Hand-written cases go BELOW the second sentinel. Everything there
is preserved byte-identically across regeneration; everything
between the sentinels is overwritten.
"""

import importlib

import pytest

# ===== AUTO-GENERATED: cross-package imports =====
CROSS_PACKAGE_IMPORTS = [
    'scitex_audio',
    'scitex_browser.debugging',
    'scitex_dev',
    'scitex_dev._cli._completion',
    'scitex_dev.cli',
    'scitex_dev.decorators',
    'scitex_logging',
]
# ===== END AUTO-GENERATED =====


@pytest.mark.parametrize("module_name", CROSS_PACKAGE_IMPORTS)
def test_cross_package_import_succeeds(module_name):
    """Importing scitex-notification's declared cross-package dependency must succeed."""
    # Arrange
    name = module_name

    # Act
    # PS-140: skip on the ROOT so a renamed submodule fails loudly
    # instead of being silently skipped; hard-import the FULL path.
    pytest.importorskip(name.split(".")[0])
    module = importlib.import_module(name)

    # Assert
    assert module is not None
